# Generated by Django 3.2.6 on 2021-10-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='date',
            field=models.DateField(null=True, verbose_name='sANA'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='info',
            field=models.TextField(verbose_name="Ma'lumot"),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='klass',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=100, verbose_name='Sinfi'),
        ),
    ]
