# Generated by Django 3.2.6 on 2021-10-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_pupil_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
